version: 2
models:
  - name: dim_rel_empresa_explotacion
sources:
  - name: aq360_silver
    database: sqld-aq-360-360-pre-01
    schema: aq360_silver
    tables: 
      - name: dim_rel_empresa_explotacion_fin
      
